### ISSUE TITLE
RuntimeError: CUDA error: initialization error

### ISSUE THREAD

**Issue by leeeeeeo** [DinoMan/face-processor#1]
At the beginning, I ran the following command, and it turns out the following error:
![image](https://user-images.githubusercontent.com/25877709/52052465-72eb0000-2591-11e9-8d48-5ee6e46711a4.png)
So I remove  `enable_cuda=cuda`, and replace it with `device='cuda'`. It works perfectly.
Then I try the video processing with the following command, and it turns out the following error and I don't know how to solve this problem.
![image](https://user-images.githubusercontent.com/25877709/52052639-fad10a00-2591-11e9-9aed-f4c771502fe0.png)
Could you please help me with solving this problem? Thank you! @DinoMan

**Comment by DinoMan** [comment]
For the first error it seems to be that the version of the face alignment library has changed the API. I will have to revise the code to reflect these changes and since the face alignment package is available via pip i will put it as a requirement. The second error may be because of the multithreading in combination with use on the GPU. i'll try to find a solution but until then you can try using the option 'cpu'
